class RepoError(Exception): pass
class RepoAlreadyExistsError(RepoError): pass
class RepoNoBackupsError(RepoError): pass
class RepoFileNotUploadedError(RepoError): pass
class RepoFileAlreadyExistsError(RepoError): pass
class RepoFileDoesNotExistLocallyError(RepoError): pass
class RepoUploadError(RepoError): pass
class RepoDownloadError(RepoError): pass
class PurgingPublishedRecordError(RepoError): pass
class NoConfigurationError(RepoError): pass
